### ISSUE TITLE
Question: Hard code Client ID and Secret

### ISSUE THREAD

**Issue by cb3inco** [autoexec-bat/sophos-central-device-migrate#1]
Is it possible to 'hardcode' the Client ID and secret in the beginning of the file? This would be helpful to run the script over and over again.

**Comment by autoexec-bat** [comment]
Yes you can do this if you desire.  Simply change the variable to a fixed value.  As an example, on line 57 where it asks for the sending tenancies Client ID, change it to the following:

send_client_id = "not-real-id123456"

Where "not-real-id123456" is your Client ID that's generated within Sophos Central.  Do similar for lines 58,63 and 64 and substituting the correct values for each (client ID, secret from each tenancy).
**WARNING!**
_Please heed the warning about having fixed credentials within 'plain text' files sitting within your environment.  If these were to fall into the wrong hands, they would provide administrative access via the API to your Sophos Central tenancies!_
